Test and lint action
ericsson-iap/go-sample-app pull request #2
Opened 2024-09-13 10:24 UTC by don2112e

Added go.yml Github Action config for tests and linting
updated server.go to pass golangci-lint 1.60.3 spec
removed file level license declarations

2024-09-13 15:27 UTC, Kristine-Saroka approved these changes
See no issues, looks good to me.

2024-09-16 08:09 UTC, kara-kiss requested changes

2024-09-16 08:09 UTC, kara-kiss commented on README.md
Looks like this change was part of a test commit to trigger github actions, and could be removed

2024-09-16 08:38 UTC, don2112e commented on README.md
Good catch, reverted

2024-09-16 08:41 UTC, kara-kiss approved these changes

2024-09-16 08:45 UTC, Kristine-Saroka approved these changes

2024-09-16 09:06 UTC, KristineSarokaESN approved these changes

2024-09-16 09:10 UTC, merged